title: "Sai Subhash Mahamkali"
description: "My journey from Undergrad to PhD: Plant genomics, fieldwork, Machine learning."
url: "https://subhashmahamkali.github.io"
baseurl: ""  
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

minimal_mistakes_skin: "dark"
collections:
  pages:
    output: true
    permalink: /:path/

include:
  - pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      toc: false
      classes: wide
