title: "Sai Subhash Mahamkali"
description: "My journey from Undergrad to PhD: genomics, fieldwork, tech."
url: "https://subhashmahamkali.github.io"
baseurl: ""   # user sites keep this empty

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# look & feel
minimal_mistakes_skin: "dark"
markdown: kramdown

# default page options
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: false
      classes: wide
